### PR TITLE
Final PCP-Min documentation

### PR DESCRIPTION
**Pull request by JacopoWolf**

### CODE REVIEW

**Review by gfurri20 — CHANGES_REQUESTED** [review]
Every variable element must be followed by a 0 (1 byte)

**Review by Alessio789 — CHANGES_REQUESTED** [review]
A byte is required at 0 after each variable field

**Review by gfurri20 — APPROVED** [review]
Approved

**Comment by JacopoWolf** [comment]
changes done! 
( everything is going according to my evil github teaching plan )

**Review by Alessio789 — APPROVED** [review]

**Pull request merged**
